---

- name: Run show commands on routers
  hosts: all


  tasks:

    - name: Get interfaces info
      cli_config:
        command: "{{ interfaces_info }}"
      register: command_output

    - name: Debug registered var
      debug:
        var: command_output.stdout_lines

